### ISSUE TITLE
Table row cell with multi line content corrupts table after page break

### ISSUE THREAD

**Issue by ChrisAtPolicyCo** [pagedjs/pagedjs#61] opened 2022-03-10 00:12 UTC
When a table row has a cell which is multi line, and there is a page break, the table is corrupted on the following page.  Please see attached image.

![image](https://user-images.githubusercontent.com/90635513/157561664-6fe36a24-ca35-46d5-ae70-4f15a8922b34.png)

**Comment by koster1996** [comment] 2022-04-11 11:23
I have the same issue, is there any resolution for this in the works?

**Comment by julientaq** [comment] 2022-04-11 15:44
Hi there.

So yes, @fchasen is working on it. 

For now, you can try using `tr {break-inside: avoid}` and tell us how that work.
Thanks!

**Comment by mccool** [comment] 2022-05-19 22:01
I tried this and it did not work. Also I have an example where it gets stuck in a loop addending dom elements

I had to add the `.txt` extension so github would allow the attachment. 

[loop_issue.html.txt](https://github.com/pagedjs/pagedjs/files/8734465/loop_issue.html.txt).

**Comment by johnlink-ferox** [comment] 2022-05-24 14:13
> For now, you can try using `tr {break-inside: avoid}` and tell us how that work. Thanks!

@julientaq I'm having the same multi-line row height corruption issue and this seems to have fixed it for me.


> Also I have an example where it gets stuck in a loop addending dom elements

@mccool I ran into a similar issue too and it seemed to happen when my content was too wide for my print page. I forced the width of my content to fit in the width of a single page and that seems to have fixed it for me. Hope that helps.

**Comment by wmbutler** [comment] 2022-05-31 20:21
@johnlink-ferox We are able to demonstrate the issue even when our content with is well under the width of the page. @fchasen I can offer a $1,000 bounty if you are able to address the issue @mccool is seeing and he accepts the solution.

**Comment by johnlink-ferox** [comment] 2022-05-31 21:16
> We are able to demonstrate the issue even when our content with is well under the width of the page. @fchasen I can offer a $1,000 bounty if you are able to address the issue @mccool is seeing and he accepts the solution.

@wmbutler I tried @mccool 's loop_issue.html.txt attachment and it's working for me just fine. One key difference is that I don't have the images available to me. So, I wonder if the images are causing problems.

If you're serious about getting the infinite loop issue fixed, I'd recommend starting a new issue. This issue was originally about about multi-line content table row corruption. You might get more eyes on a fresh issue with a more accurate title about infinite looping.

**Comment by julientaq** [comment] 2022-05-31 21:32
I was looking into the issue too, but  i’ll have a proper look tomorrow (it’s almost midnight here).

Meantime, if there are images in the html, i need em too. @mccool Please open a new issue with your html, your css and your images / script so we can try to reproduce. 

I keep this issue about table open because it’s not a fix but a workaround. forcing `break-inside: avoid` isn’t very good imho.

**Comment by wmbutler** [comment] 2022-05-31 22:40
Let's focus on the table break issue. We can always circle back to the images if the problem remains. I've asked @mccool to provide some source without the images that we can confirm are breaking. Look for his follow-up shortly.

**Comment by wmbutler** [comment] 2022-06-01 13:48
It looks like the pagedjs logic is closing out the table, but it's failing to reopen the table with the two additional <td> tags needed to recreate the table correctly on the next page.

**Comment by wmbutler** [comment] 2022-06-02 15:18
@julientaq were you able to reproduce this table breaking issue with my stackblitz and the files provided? Bumping the bounty to $1500.

**Comment by wmbutler** [comment] 2022-06-03 18:25
@julientaq bumping this bounty to $2,000.

**Comment by julientaq** [comment] 2022-06-03 19:33
Hey @wmbutler we’ll come back next week with more infos about what we can do about it and how we can proceed, we’re looking into it.

**Comment by wmbutler** [comment] 2022-06-06 23:04
@julientaq Thanks. It's interesting. Seems to be that the logic rests in the page break and then how the table knows to reconstruct itself after a page break. The html is correct prior to pagedjs.

```
<table>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
</table>
```

But, pagedjs  seems to not understand that when there is a page break, the table needs to be reconstructed with all 3 <td> elements. Instead it constructs it with just 1 <td>.

```
<table>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
</table>

<~--- PAGE BREAK --->

<table>
<tr>
<td></td>
</tr>
</table>

```

**Comment by wmbutler** [comment] 2022-06-10 15:43
Tables are mandatory. I think I'll try a different approach on the bounty. I'm going to set the bounty now to **$5,000**. I'll reduce it by $500 each week. Thanks for looking into this @julientaq. Next reduction is June 17 23:59:59 UTC.

**Comment by NigelCunningham** [comment] 2022-08-24 11:55
Hi all.

I've prepared a patch which fixes this issue, which I'm now turning into a PR (link coming).

The bulk of the patch modifies the check for overflow so that it doesn't just consider the left and right sides of the page, but also the top and bottom (I don't understand why it didn't do both before, but there you go!).

The second and tiny part is a change to the 'insideTableCell' logic so that rather than taking just the offending table cell to the next page, we take it's parent (probably the TR) and all of its siblings. This fixes the issue with previous table cells being rendered at the bottom of the first page being processed, and the offending cell and later siblings being placed on the next page.

**Closed** 2022-08-30 20:03 UTC

**Comment by mccool** [comment] 2022-08-30 21:29
@johnlink-ferox @julientaq Sorry guys about the no response. I did not get any notifications from GitHub about being mentioned here. I'm double checking my notification settings so that I we be more on top of things here.
