### ISSUE TITLE
Specific content can trigger an endless loop of creating new print pages, eventually killing the browser

### ISSUE THREAD

**Issue by mflorea** [pagedjs/pagedjs#111] opened 2022-10-25 15:54 UTC
The problem can be reproduced on both Firefox and Chrome with this HTML:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <script src="/path/to/pagedjs/0.3.5/dist/paged.polyfill.js"></script>
  </head>
  <body>
    <p>1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7<br/>8<br/>9<br/>10<br/>11<br/>12<br/>13<br/>14<br/>15<br/>16<br/>17<br/>18<br/>19<br/>20<br/>21<br/>22<br/>23<br/>24<br/>25<br/>26<br/>27<br/>28<br/>29<br/>30<br/>31<br/>32<br/>33<br/>34<br/>35<br/>36<br/>37<br/>38<br/>39<br/>40<br/>41<br/>42<br/>43<br/>44<br/>45<br/>46<br/>47<br/>48<br/>49<br/>50<br/>1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7<br/>8<br/>9<br/>10<br/>11<br/>12<br/>13<br/>14<br/>15<br/>16<br/>17<br/>18<br/>19<br/>20<br/>21<br/>22<br/>23<br/>24<br/>25<br/>26<br/>27<br/>28<br/>29<br/>30<br/>31<br/>32<br/>33<br/>34<br/>35<br/>36<br/>37<br/>38<br/>39<br/>40<br/>41<br/>42<br/>43<br/>44<br/>45<br/>46<br/>47<br/>48<br/>49<br/>50</p>
  </body>
</html>
```

What's crazy is that the following HTML doesn't trigger the issue:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <script src="/path/to/pagedjs/0.3.5/dist/paged.polyfill.js"></script>
  </head>
  <body>
    <p>1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7<br/>8<br/>9<br/>10<br/>11<br/>12<br/>13<br/>14<br/>15<br/>16<br/>17<br/>18<br/>19<br/>20<br/>21<br/>22<br/>23<br/>24<br/>25<br/>26<br/>27<br/>28<br/>29<br/>30<br/>31<br/>32<br/>33<br/>34<br/>35<br/>36<br/>37<br/>38<br/>39<br/>40<br/>41<br/>42<br/>43<br/>44<br/>45<br/>46<br/>47<br/>48<br/>49<br/>50<br/>51<br/>52<br/>53<br/>54<br/>55<br/>56<br/>57<br/>58<br/>59<br/>60<br/>61<br/>62<br/>63<br/>64<br/>65<br/>66<br/>67<br/>68<br/>69<br/>70<br/>71<br/>72<br/>73<br/>74<br/>75<br/>76<br/>77<br/>78<br/>79<br/>80<br/>81<br/>82<br/>83<br/>84<br/>85<br/>86<br/>87<br/>88<br/>89<br/>90<br/>91<br/>92<br/>93<br/>94<br/>95<br/>96<br/>97<br/>98<br/>99<br/>00</p>
  </body>
</html>
```

Note that in the past I was able to reproduce the same problem (endless loop of creating new print pages) using other HTML (e.g. large tables) but I was able to overcome the problem using some CSS. In this case I have no option because the issue doesn't seem related to the CSS.

**Comment by mflorea** [comment] 2022-10-27 09:30
The same issue has been reported on https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/363 .

**Comment by vidoardes** [comment] 2022-11-01 20:43
I have also seen this issue but haven't been able to narrow down the cause - I initially put it down to malformed HTML (missing end tag for example) but I'm glad to know I'm not the only one!

**Comment by julientaq** [comment] 2023-01-17 12:15
Thanks.

we’re closing this issue and check the other side of the pond.

**Closed by julientaq** 2023-01-17 12:15 UTC
