### ISSUE TITLE
Page breaks between flex DIV or Table row

### ISSUE THREAD

**Issue by Justinrds01** [pagedjs/pagedjs#113] opened 2022-11-30 13:16 UTC
I have a collection of div elements, that should simulate a table rows, this is the structure of a row and its properties:

```
<div class="row">
   <div class="column">
      :content
   </div>
   <div class="column">
       :content
   </div>
</div>
```
```
.row {
   display: flex
}

.column {
   flex: 1 1 0;
}
```

Whenever one of these rows get split between pages, you would expect the splitted row to keep te same amount of cells as the previous row. However, the cells that don't have enough content to split, get removed/ignored in the second page:

![image](https://user-images.githubusercontent.com/105781149/204999993-04c2af3b-ead8-416d-a801-8018faf34576.png)

As far as I have seen and tested, table rows (tr elements) have the same behaviour when they get split. I feel like it should insert an empty cell where needed on the second page, to preserve the structure of the row.

Right now I manipulate the DOM to insert the empty cell(s) to fix this behaviour, but it would be a nice addition for Paged JS to process these row breaks automatically.

**Comment by adeiming** [comment] 2022-12-12 02:18
same here

**Comment by julientaq** [comment] 2023-01-17 12:13
hi there

duplicate of https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/85

**Closed** 2023-01-17 12:13 UTC
