### ISSUE TITLE
string-set use

### ISSUE THREAD

**Issue by sapyx** [pagedjs/pagedjs#19] opened 2020-05-25 11:07 UTC
I tried to use the `string-set `command in the `string-set: chapter attr(data-toc-title);` form, but the string that comes back to me is as if I had used the `string-set: chapter content(text)`; form

My CSS:
```
article h1 {
        string-set: chapter attr("data-toc-title");
}
```
My Html:
`<h1 class="title-element" data-title-level="1" data-toc-title="Pro­get­ta­zio­ne" id="title-element-3" data-ref="66e0aab0-9f43-41ef-bdc0-ab1ace9c693a" data-id="title-element-3" data-break-before="right" data-counter-titlelevel1-increment="1" data-counter-increment="titleLevel1" data-counter-titlelevel1-value="5" data-counter-titlelevel2-reset="0" data-counter-reset="titleLevel2">Pro­get­ta­zio­ne con­sa­pe­vo­le</h1>`

**Comment by julientaq** [comment] 2020-05-25 11:22
Hi sapyx!

The `string-set attr()` function is still in development. 

It’s a duplicate of this https://gitlab.pagedmedia.org/tools/pagedjs/issues/42 
You can follow the update on the gitlab.

We’ll put some `potion magique` in our dev drinks so we can update that quickly :)

**Closed** 2020-06-11 08:46 UTC
